/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotelmangmentsoftware;

import javax.swing.JOptionPane;

/**
 *
 * @author SAM
 */
public class Add_Room extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Hotel hotel;

    public Add_Room(Hotel hotel) {
        this.hotel = hotel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        AddRoom_Price_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AddRoom_AddRoom_Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AddRoom_Size_TextField = new javax.swing.JTextField();
        AddRoom_Beds_TextField = new javax.swing.JTextField();
        back_BTN = new javax.swing.JButton();
        back_BTN.setText("Back");
        back_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BTNActionPerformed(evt);
            }
        });


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 241, 254));

        kGradientPanel1.setkEndColor(new java.awt.Color(246, 241, 254));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 10, 128));

        AddRoom_Price_TextField.setBackground(new java.awt.Color(246, 241, 254));
        AddRoom_Price_TextField.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        AddRoom_Price_TextField.setForeground(new java.awt.Color(20, 3, 43));
        AddRoom_Price_TextField.setBorder(null);
        AddRoom_Price_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoom_Price_TextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel3.setText("Price");

        jLabel2.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel2.setText("Beds");

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 3, 43));
        jLabel1.setText("Add Room");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(43, 16));

        AddRoom_AddRoom_Button.setText("Add Room");
        AddRoom_AddRoom_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoom_AddRoom_ButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel4.setText("size");

        AddRoom_Size_TextField.setBackground(new java.awt.Color(246, 241, 254));
        AddRoom_Size_TextField.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        AddRoom_Size_TextField.setForeground(new java.awt.Color(20, 3, 43));
        AddRoom_Size_TextField.setBorder(null);
        AddRoom_Size_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoom_Size_TextFieldActionPerformed(evt);
            }
        });

        AddRoom_Beds_TextField.setBackground(new java.awt.Color(246, 241, 254));
        AddRoom_Beds_TextField.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        AddRoom_Beds_TextField.setForeground(new java.awt.Color(20, 3, 43));
        AddRoom_Beds_TextField.setBorder(null);
        AddRoom_Beds_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoom_Beds_TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(323, 323, 323))
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(330, 330, 330)
                                                .addComponent(AddRoom_AddRoom_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(back_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(309, 309, 309)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel4)
                                                        .addComponent(AddRoom_Size_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(AddRoom_Price_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(AddRoom_Beds_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(158, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddRoom_Beds_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddRoom_Price_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddRoom_Size_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AddRoom_AddRoom_Button)
                                        .addComponent(back_BTN))
                                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddRoom_Price_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoom_Price_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddRoom_Price_TextFieldActionPerformed

    private void AddRoom_AddRoom_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoom_AddRoom_ButtonActionPerformed
        // TODO add your handling code here:
        try {
            int beds = Integer.parseInt(AddRoom_Price_TextField.getText());
            int price = Integer.parseInt(AddRoom_Price_TextField.getText());
            int size = Integer.parseInt(AddRoom_Size_TextField.getText());

            // Assuming the type is a predefined value or needs to be set manually
            String type = "Standard"; // Replace with actual logic to determine the room type if needed

            Room newRoom = new Room(type, beds, size, price);
            if (!AddRoom_Beds_TextField.getText().isEmpty()) {
                try {
                    beds = Integer.parseInt(AddRoom_Beds_TextField.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid number for beds", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if (!AddRoom_Price_TextField.getText().isEmpty()) {
                try {
                    price = Integer.parseInt(AddRoom_Price_TextField.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid number for price", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if (!AddRoom_Price_TextField.getText().isEmpty()) {
                try {
                    price = Integer.parseInt(AddRoom_Price_TextField.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid number for price", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if (hotel.addRoom(newRoom)) {
                JOptionPane.showMessageDialog(this, "Room added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new Hotel_Home_Page(hotel).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add room.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for beds, price, and size.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddRoom_AddRoom_ButtonActionPerformed

    private void AddRoom_Size_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoom_Size_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddRoom_Size_TextFieldActionPerformed

    private void AddRoom_Beds_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoom_Beds_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddRoom_Beds_TextFieldActionPerformed

    private void Back_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Hotel_Home_Page(hotel).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        Hotel exampleHotel = new Hotel("ExampleHotel", "password", 1, "Example Location", "Example Country", "Example City");

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Add_Room(exampleHotel).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRoom_AddRoom_Button;
    private javax.swing.JButton back_BTN;
    private javax.swing.JTextField AddRoom_Beds_TextField;
    private javax.swing.JTextField AddRoom_Price_TextField;
    private javax.swing.JTextField AddRoom_Size_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
