
package com.mycompany.hotelmangmentsoftware;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JOptionPane;

/**
 *
 * @author SAM
 */
public class Hotel_Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Hotel hotel;

    public Hotel_Home_Page(Hotel user) {
        initComponents();
        this.hotel = user; // Store the logged-in user instance
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        HHome_ViewBooking_Button = new javax.swing.JButton();
        HHome_AddRoom_Button = new javax.swing.JButton();
        HHome_DeleteRoom_Button = new javax.swing.JButton();
        HHome_ViewFeedbacks_Button = new javax.swing.JButton();
        HHome_ID_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        back_BTN = new javax.swing.JButton();

        back_BTN.setText("Logout");
        back_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_BTNActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 241, 254));

        kGradientPanel1.setkEndColor(new java.awt.Color(246, 241, 254));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 10, 128));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 3, 43));
        jLabel1.setText("Logged Successfully");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(43, 16));

        HHome_ViewBooking_Button.setText("View Booking");
        HHome_ViewBooking_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HHome_ViewBooking_ButtonActionPerformed(evt);
            }
        });

        HHome_AddRoom_Button.setText("Add Room");
        HHome_AddRoom_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HHome_AddRoom_ButtonActionPerformed(evt);
            }
        });

        HHome_DeleteRoom_Button.setText("Delete Room");
        HHome_DeleteRoom_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HHome_DeleteRoom_ButtonActionPerformed(evt);
            }
        });

        HHome_ViewFeedbacks_Button.setText("View Feedbacks");
        HHome_ViewFeedbacks_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HHome_ViewFeedbacks_ButtonActionPerformed(evt);
            }
        });

        HHome_ID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HHome_ID_TextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addContainerGap(243, Short.MAX_VALUE)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                                .addComponent(HHome_ViewBooking_Button)
                                                .addGap(347, 347, 347))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addComponent(back_BTN)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(HHome_ViewFeedbacks_Button)
                                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                                .addGap(13, 13, 13)
                                                                                .addComponent(HHome_AddRoom_Button)))
                                                                .addGap(73, 73, 73)
                                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(HHome_DeleteRoom_Button)
                                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel2)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(HHome_ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(259, 259, 259))))
        );
        kGradientPanel1Layout.setVerticalGroup(
                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(back_BTN)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HHome_ViewBooking_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(HHome_AddRoom_Button)
                                        .addComponent(HHome_ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(HHome_DeleteRoom_Button)
                                        .addComponent(HHome_ViewFeedbacks_Button))
                                .addContainerGap(203, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HHome_ViewBooking_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HHome_ViewBooking_ButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new View_Booking(hotel).setVisible(true);
    }//GEN-LAST:event_HHome_ViewBooking_ButtonActionPerformed

    private void HHome_AddRoom_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HHome_AddRoom_ButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Add_Room(hotel).setVisible(true); // It needs an Argument . we won't add on we will just change the Add_Room to take the last user who logged in from Database.
    }//GEN-LAST:event_HHome_AddRoom_ButtonActionPerformed

    private void HHome_ViewFeedbacks_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HHome_ViewFeedbacks_ButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Feedback_List(hotel).setVisible(true);
    }//GEN-LAST:event_HHome_ViewFeedbacks_ButtonActionPerformed

    private void HHome_DeleteRoom_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HHome_DeleteRoom_ButtonActionPerformed
        // TODO add your handling code here:
        if (HHome_ID_TextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter an ID Please", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int returnQuery = hotel.removeRoom(Integer.parseInt(HHome_ID_TextField.getText()));

        if(returnQuery == 1){
            JOptionPane.showMessageDialog(this, "Room Deleted Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        }
        else if(returnQuery == 0){
            JOptionPane.showMessageDialog(this, "Already Booked Can't Be Deleted!", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(returnQuery == -1){
            JOptionPane.showMessageDialog(this, "Invalid ID", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_HHome_DeleteRoom_ButtonActionPerformed

    private void HHome_ID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HHome_ID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HHome_ID_TextFieldActionPerformed
    private void back_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Home_Page().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Hotel_Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_BTN;
    private javax.swing.JButton HHome_AddRoom_Button;
    private javax.swing.JButton HHome_DeleteRoom_Button;
    private javax.swing.JTextField HHome_ID_TextField;
    private javax.swing.JButton HHome_ViewBooking_Button;
    private javax.swing.JButton HHome_ViewFeedbacks_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
